name: test
on: [ push, pull_request ]
jobs:
  windows-x86:
    name: windows (x86)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86
  windows-x86_64:
    name: windows (x86_64)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86_64
  windows-mingw:
    name: windows (mingw)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        path: luamake
        repository: actboy168/luamake
        submodules : recursive
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-ninja
    - shell: msys2 {0}
      working-directory: luamake
      run: ./compile/build.sh notest
    - shell: msys2 {0}
      run: ./luamake/luamake
  macos-x86_64:
    name: macos (x86_64)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86_64
  macos-arm64:
    name: macos (arm64)
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch arm64
  linux-x86_64:
    name: linux (x86_64)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: actboy168/setup-luamake@master
    - run: luamake
    - run: luamake lua test/glibc-version.lua
  linux:
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, armv7, riscv64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          dockerRunArgs: |
            --volume "${PWD}:/actboy168"
          install: |
            apt-get update -q -y
            apt-get install -q -y gcc g++ ninja-build
          run: |
            pushd luamake
            ./compile/build.sh notest
            popd
            ./luamake/luamake
